# Site settings
# These are used to personalize your new site.
logo: "/images/flight_suit_profile.jpg?raw=true" # your photo (or logo) here
title: Micah Stargel # your name here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2023)
  <br /><br />
  <a href="/pdf/Stargel Resume Spring 2023.pdf">View My Resume</a>
  <br /><br />
  <a href="https://app.joinhandshake.com/stu/users/25817292/">View My Handshake Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  mdstargel # update with your username

# Build setting
theme: jekyll-theme-minimal

