# Site settings
# These are used to personalize your new site.
logo: "/images/flight_suit_profile2.jpg?raw=true" # your photo (or logo) here
title: Micah"\'"s Portfolio # your name here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  <a href="/"><h2 style="font-size: 30px">Micah Stargel</h2></a><b>
  <br />
  <b>CSCI 496: Senior Portfolio</b><br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2023)<br />
  <br />
  <a href="/pdf/Stargel Resume Spring 2023.pdf">View My Resume</a><br />
  <br />
  <a href="https://app.joinhandshake.com/stu/users/25817292/">View My Handshake Profile</a>
repository: "mdstargel/mdstargel.github.io"
github_username:  mdstargel # update with your username

# Build setting
theme: jekyll-theme-minimal

plugins:
  - jekyll-titles-from-headings
